# Lab 02: Manipulate PyTorch Tensors -- exercise

In [1]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [3]:

# write your code here
A=torch.Tensor( [ [1,2] , [3,4] ] )
B=torch.Tensor( [ [10,20], [30, 40] ] )
C = A + B
print(C)



tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [4]:

# write your code here
print(A.dim())
print(A.size()) 
print(A.type())


2
torch.Size([2, 2])
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [5]:

# write your code here
A = A.long()
print(A)
print(A.type())


tensor([[1, 2],
        [3, 4]])
torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [9]:

# write your code here
A=torch.rand(5,2,3)
print(A)
print(A.type())
print(A.dim()) 
print(A.size())
print(A.size(1))
# 5 x 2 x 3 is like, 5 matrices each with 2 rows and 3 columns


tensor([[[2.4663e-01, 9.2605e-01, 3.0750e-01],
         [7.6446e-01, 2.2615e-01, 3.9884e-02]],

        [[8.4381e-01, 1.7174e-01, 8.2358e-01],
         [1.9213e-01, 2.2285e-01, 1.8092e-01]],

        [[1.9199e-04, 9.4128e-01, 7.7156e-01],
         [2.2442e-01, 3.4365e-01, 1.1506e-01]],

        [[5.0262e-01, 9.7712e-01, 2.1069e-01],
         [7.9355e-01, 9.1445e-01, 1.6550e-01]],

        [[9.6353e-01, 4.5749e-01, 5.5669e-01],
         [4.8314e-01, 9.7213e-02, 2.6389e-01]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
tensor([[0.8438, 0.1717, 0.8236],
        [0.1921, 0.2228, 0.1809]])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [7]:

# write your code here
A=torch.zeros(2,3,4,5)
print(A)


tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
