# Lab 01 : Linear module -- demo

In [1]:
import torch
import torch.nn as nn

### Make a _Linear Module_ that takes input of size 5 and return output of size 3

In [2]:
mod = nn.Linear(5,3)
print(mod)

Linear(in_features=5, out_features=3, bias=True)


### Let's make a random tensor of size 5:

In [3]:
x=torch.rand(5)
print(x)
print(x.size())

tensor([0.6873, 0.3363, 0.9933, 0.6856, 0.5915])
torch.Size([5])


### Feed it to the module:

In [4]:
y=mod(x)
print(y)

tensor([ 0.3188, -0.3233, -0.8608], grad_fn=<AddBackward0>)


### The output y is computed according to the formula:
$$
\begin{bmatrix}
y_1\\ y_2 \\y_3 
\end{bmatrix} =
\begin{bmatrix}
w_{11} & w_{12} & w_{13}& w_{14}& w_{15} \\
w_{21} & w_{22} & w_{23}& w_{24}& w_{25} \\
w_{31} & w_{32} & w_{33}& w_{34}& w_{35} \\
\end{bmatrix}
\begin{bmatrix}
x_1\\ x_2 \\x_3 \\ x_4 \\x_5
\end{bmatrix}
+
\begin{bmatrix}
b_1\\ b_2 \\b_3 
\end{bmatrix}
$$
### were the $w_{ij}$'s are the weight parameters and the $b_i$'s are the bias parameters. These internal parameters can be access as follow:

In [5]:
print(mod.weight)
print(mod.weight.size())

Parameter containing:
tensor([[ 0.0447,  0.2874,  0.1906,  0.0898,  0.0092],
        [-0.0742, -0.1195,  0.2347, -0.1140, -0.0454],
        [-0.0169, -0.0507, -0.2991,  0.0503, -0.3686]], requires_grad=True)
torch.Size([3, 5])


In [6]:
print(mod.bias)
print(mod.bias.size())

Parameter containing:
tensor([-0.0649, -0.3602, -0.3514], requires_grad=True)
torch.Size([3])


### If we want we can change the internal parameters of the module:

In [7]:
with torch.no_grad():
    mod.weight[0,0]=0
    mod.weight[0,1]=1
    mod.weight[0,2]=2
    print(mod.weight)

Parameter containing:
tensor([[ 0.0000,  1.0000,  2.0000,  0.0898,  0.0092],
        [-0.0742, -0.1195,  0.2347, -0.1140, -0.0454],
        [-0.0169, -0.0507, -0.2991,  0.0503, -0.3686]], requires_grad=True)


### We can also make a Linear module without bias:

In [8]:
mod2 = nn.Linear(5,3,bias=False)
print(mod2)

Linear(in_features=5, out_features=3, bias=False)


In [9]:
print(mod2.weight)

Parameter containing:
tensor([[-0.4082, -0.2345,  0.3771, -0.3740, -0.4435],
        [-0.1758,  0.0394,  0.4464,  0.0982, -0.1037],
        [-0.2344,  0.0434, -0.0137, -0.2479, -0.3998]], requires_grad=True)


In [10]:
print(mod2.bias)

None
