# Lab 03 : Vanilla neural networks -- exercise

# Creating a one-layer network

In [1]:
import torch
import torch.nn as nn

### Make a class for a one layer network. Let's call the layer "mylayer". And let's give it a bias.

In [5]:
class one_layer_net(nn.Module):

    def __init__(self,  input_size, output_size  ):
        super(one_layer_net , self).__init__()
        
        self.layer1 = nn.Linear( input_size, output_size , bias=True) 
        
        
    def forward(self, x):
        
        x = self.layer1(x)
        p = torch.softmax(x, dim=0) #note that it always ends with softmax, relu is for the intermediate layers
        
        return p

### Create an instance of a one layer net that take input of size 2 and return output of size 2

In [6]:
net= one_layer_net(2,2)
print(net)

one_layer_net(
  (layer1): Linear(in_features=2, out_features=2, bias=True)
)


### Make a vector $x=\begin{bmatrix}1\\1 \end{bmatrix}$ and feed it to the network. What is the output probability? Check that it sums to one.

In [7]:
x=torch.Tensor([1,1])
print(x)

p=net.forward(x)
print(p)

print(p.sum() )

tensor([1., 1.])
tensor([0.5426, 0.4574], grad_fn=<SoftmaxBackward>)
tensor(1., grad_fn=<SumBackward0>)


### Print the weights as well as the bias of the unique layer of this network. Be careful to use the correct name for this unique layer 

In [9]:
print(net.layer1.weight)
print(net.layer1.bias)

Parameter containing:
tensor([[ 0.1960,  0.0604],
        [-0.0346, -0.2190]], requires_grad=True)
Parameter containing:
tensor([-0.1732,  0.1659], requires_grad=True)


### Change the internal parameters of your network so that the weights are now equal to $
W=\begin{bmatrix}
1&2 \\ 3&4 
\end{bmatrix}
$ and the bias is equal to  $
b=\begin{bmatrix}
1 \\ 1 
\end{bmatrix}
$ 

In [14]:
with torch.no_grad():
    net.layer1.weight[0,0]=1
    net.layer1.weight[0,1]=2
    net.layer1.weight[1,0]=3
    net.layer1.weight[1,1]=4

    net.layer1.bias[0] = 1
    net.layer1.bias[1] = 1

    print(net.layer1.weight)
    print(net.layer1.bias)

Parameter containing:
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
Parameter containing:
tensor([1., 1.], requires_grad=True)


### Feed the vector x to your network with updated parameters. What is the output? (you should get p= [2% 98%])

In [15]:
p= net.forward(x)
print(p)

tensor([0.0180, 0.9820], grad_fn=<SoftmaxBackward>)
