# Lab 03 : Vanilla neural networks -- demo

# Creating a two-layer network

In [1]:
import torch
import torch.nn as nn

### In Pytorch, networks are defined as classes

In [2]:
class two_layer_net(nn.Module):

    def __init__(self, input_size, hidden_size, output_size):
        super(two_layer_net , self).__init__()
        
        self.layer1 = nn.Linear( input_size, hidden_size , bias=True)
        self.layer2 = nn.Linear( hidden_size, output_size , bias=True)        
        
    def forward(self, x):
        
        x = self.layer1(x)
        x = torch.relu(x)
        x = self.layer2(x)
        p = torch.softmax(x, dim=0)
        
        return p

### Create an instance that takes input of size 2, then transform it into something of size 5, then into something of size 3
$$
\begin{bmatrix}
\times \\ \times 
\end{bmatrix}
\longrightarrow
\begin{bmatrix}
\times \\ \times \\ \times \\ \times \\ \times
\end{bmatrix}
\longrightarrow
\begin{bmatrix}
\times \\ \times \\ \times
\end{bmatrix}
$$

In [3]:
net= two_layer_net(2,5,3)
print(net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### Now we are going to make an input vector and feed it to the network:

In [4]:
x=torch.Tensor([1,1])
print(x)

tensor([1., 1.])


In [5]:
p=net.forward(x)
print(p)

tensor([0.3757, 0.1835, 0.4408], grad_fn=<SoftmaxBackward>)


### Syntactic easy for the forward method

In [6]:
p=net(x)
print(p)

tensor([0.3757, 0.1835, 0.4408], grad_fn=<SoftmaxBackward>)


### Let's check that the probability vector indeed sum to 1:

In [7]:
print( p.sum() )

tensor(1.0000, grad_fn=<SumBackward0>)


### This network is composed of two Linear modules that we have called layer1 and layer2. We can see this when we type:

In [8]:
print(net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### We can access the first module as follow:

In [9]:
print(net.layer1)

Linear(in_features=2, out_features=5, bias=True)


### To get the weights and bias of the first layer we do:

In [10]:
print(net.layer1.weight)

Parameter containing:
tensor([[ 0.0012, -0.6405],
        [ 0.6564,  0.0672],
        [ 0.0340,  0.3796],
        [-0.2548,  0.0915],
        [-0.0329,  0.5431]], requires_grad=True)


In [11]:
print(net.layer1.bias)

Parameter containing:
tensor([ 0.4953,  0.1759, -0.5314, -0.0482,  0.3979], requires_grad=True)


### So to change the first row of the weights from layer 1 you would do:

In [12]:
with torch.no_grad():
    net.layer1.weight[0,0]=10
    net.layer1.weight[0,1]=20
    print(net.layer1.weight)

Parameter containing:
tensor([[10.0000, 20.0000],
        [ 0.6564,  0.0672],
        [ 0.0340,  0.3796],
        [-0.2548,  0.0915],
        [-0.0329,  0.5431]], requires_grad=True)


### Now we are going to feed  $x=\begin{bmatrix}1\\1 \end{bmatrix}$ to this modified network:

In [13]:
p=net(x)
print(p)

tensor([1.2272e-06, 1.9272e-02, 9.8073e-01], grad_fn=<SoftmaxBackward>)


### Alternatively, all the parameters of the network can be accessed by net.parameters(). 

In [14]:
list_of_param = list( net.parameters() )
print(list_of_param)

[Parameter containing:
tensor([[10.0000, 20.0000],
        [ 0.6564,  0.0672],
        [ 0.0340,  0.3796],
        [-0.2548,  0.0915],
        [-0.0329,  0.5431]], requires_grad=True), Parameter containing:
tensor([ 0.4953,  0.1759, -0.5314, -0.0482,  0.3979], requires_grad=True), Parameter containing:
tensor([[-0.1319, -0.0678, -0.0144, -0.0875,  0.3871],
        [ 0.2085, -0.3780, -0.1121,  0.4165, -0.0244],
        [ 0.3086, -0.1498,  0.2259, -0.0276,  0.3088]], requires_grad=True), Parameter containing:
tensor([-0.3721, -0.4362, -0.0674], requires_grad=True)]
